/**
 * Created by schang124 on 2017/05/17.
 */

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_REGISTER = "AUTH_LOGIN";
export const AUTH_REGISTER_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

export const NAV_INIT = "NAV_INIT";
export const NAV_OPEN = "NAV_OPEN";
export const NAV_CLOSE = "NAV_CLOSE";
